sudo: required

services:
  - docker

install:
  - docker build -t lgatica/https-proxy-alpine:latest .

script:
  - docker run --rm lgatica/https-proxy-alpine:latest haproxy -v

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push lgatica/https-proxy-alpine:latest
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false